apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: moon
spec:
  storageClassName: standard
  volumeName: data-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi